services:
  - type: web
    name: mri-tumor-scanner-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd src/api && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000

